### ISSUE TITLE
Does not render TRANSCRIPT when transcript is added after original ingest

### ISSUE THREAD

**Issue by bradspry** [digitalutsc/islandora_solution_pack_oralhistories#2] opened 2015-03-31 18:38 UTC
Using Islandora Batch, it's possible to populate a collection with lightweight, metadata-only records, using a zipfile containing only MODS .xml files.

At a later date, one can add the WAV OBJ, and the system successfully generates derivative datastreams, such as PROXY_MP3.

Apparently, the system does not render the TRANSCRIPT if the transcript is added at a later date.

Steps to reproduce:
1. Collection > Batch Ingest zipfile containing only MODS .xml files
2. Object > Manage > Datastreams > Add a datastream
3. Add TRANSCRIPT dsid and attach .vtt file, then upload
4. Transcript datastream is created and added successfully, but transcript does not render to page; <div id="transcript-content"></div> is empty.

**Comment by MarcusBarnes** [comment] 2016-10-07 15:19
Both @Natkeeran and myself have been unable to reproduce using the latest work b6a00b616b2668ef8ffa681bdbaa84437c8a94be.   @bradspry Would you be able to pull the most recent version and see if you're still getting the same behavior?   I'm going to close this issue until we are able to reproduce from the more recent work.  Thank you for understanding.

**Closed as completed by MarcusBarnes** 2016-10-07 15:19 UTC
